### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by ccampo133**
Just some refactoring and small fixes pointed out in my [comment on reddit](https://www.reddit.com/r/millionairemakers/comments/2s1m3u/drawing_system_source_code_released/cnndyz7). I still need to work out the authentication stuff, but this is a start.

### CODE REVIEW

**Comment by minlite** [comment]
Thanks for the PR. It is giving out the following warning. Is it normal?

```
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/mpl_toolkits': missing   __init__.py
file, filename, etc = imp.find_module(subname, path)
```

**Comment by ccampo133** [comment]
Not sure why this is happening at the moment. Let me take a look.

**Comment by ccampo133** [comment]
OK that should fix it if you aren't using virtualenv. You should probably use virtualenv though :)

**Comment by minlite** [comment]
Awesome. Thanks! I should read more about virtualenvs... :+1:

**Pull request merged**
